name = "pathofkings"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[vars]
PBKDF2_ITERATIONS = "100000"

[[d1_databases]]
binding = "DB"
database_name = "pathofkings"
database_id = "80e04337-9f01-49f1-900f-ba8045dafaef"

